"""add agent video generation fields

Revision ID: 3237af62fd9d
Revises: f1a2b3c4d5e7
Create Date: 2026-07-25 21:49:44.941264
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3237af62fd9d'
down_revision: str | None = 'f1a2b3c4d5e7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('external_job_id', sa.String(length=255), nullable=True))
    op.add_column(
        'agents',
        sa.Column('kind', sa.String(length=20), nullable=False, server_default='chat'),
    )
    op.add_column('agents', sa.Column('video_size', sa.String(length=20), nullable=True))
    op.add_column('agents', sa.Column('video_seconds', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'video_seconds')
    op.drop_column('agents', 'video_size')
    op.drop_column('agents', 'kind')
    op.drop_column('agent_runs', 'external_job_id')
    # ### end Alembic commands ###
