"""restructure orders table with typed columns

Revision ID: 33f5d69cc60e
Revises: c54a01238a81
Create Date: 2026-07-24 14:48:00.751376
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "33f5d69cc60e"
down_revision: str | None = "c54a01238a81"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("external_company_id", sa.Uuid(), nullable=False))
    op.add_column("orders", sa.Column("code", sa.Integer(), nullable=True))
    op.add_column("orders", sa.Column("origin", sa.String(length=255), nullable=True))
    op.add_column("orders", sa.Column("observations", sa.String(), nullable=True))
    op.add_column("orders", sa.Column("external_created_at", sa.DateTime(), nullable=True))
    op.add_column("orders", sa.Column("external_updated_at", sa.DateTime(), nullable=True))
    op.add_column("orders", sa.Column("expires_at", sa.DateTime(), nullable=True))
    op.add_column(
        "orders", sa.Column("customer", postgresql.JSONB(astext_type=sa.Text()), nullable=False)
    )
    op.add_column(
        "orders", sa.Column("products", postgresql.JSONB(astext_type=sa.Text()), nullable=False)
    )
    op.add_column(
        "orders", sa.Column("address", postgresql.JSONB(astext_type=sa.Text()), nullable=False)
    )
    op.add_column(
        "orders", sa.Column("freight", postgresql.JSONB(astext_type=sa.Text()), nullable=False)
    )
    op.add_column(
        "orders", sa.Column("seller", postgresql.JSONB(astext_type=sa.Text()), nullable=False)
    )
    op.add_column(
        "orders", sa.Column("payment", postgresql.JSONB(astext_type=sa.Text()), nullable=False)
    )
    op.add_column(
        "orders", sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "summary")
    op.drop_column("orders", "payment")
    op.drop_column("orders", "seller")
    op.drop_column("orders", "freight")
    op.drop_column("orders", "address")
    op.drop_column("orders", "products")
    op.drop_column("orders", "customer")
    op.drop_column("orders", "expires_at")
    op.drop_column("orders", "external_updated_at")
    op.drop_column("orders", "external_created_at")
    op.drop_column("orders", "observations")
    op.drop_column("orders", "origin")
    op.drop_column("orders", "code")
    op.drop_column("orders", "external_company_id")
    # ### end Alembic commands ###
