"""add brand archetype profiles

Revision ID: 86793f04d035
Revises: 2b3c4d5e6f70
Create Date: 2026-07-25 20:01:36.686505
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86793f04d035'
down_revision: str | None = '2b3c4d5e6f70'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_archetype_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('primary_archetype', sa.String(length=50), nullable=False),
    sa.Column('secondary_archetype', sa.String(length=50), nullable=True),
    sa.Column('archetype_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('core_desire', sa.String(length=500), nullable=True),
    sa.Column('fear', sa.String(length=500), nullable=True),
    sa.Column('strategy', sa.String(length=500), nullable=True),
    sa.Column('voice', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('audience', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('messaging_pillars', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('guardrails', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reference_examples', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='fk_brand_archetype_profiles_company_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brand_archetype_profiles')
    # ### end Alembic commands ###
