"""add agent video provider

Revision ID: 258cfe408daa
Revises: 3237af62fd9d
Create Date: 2026-07-25 22:45:00.743333
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '258cfe408daa'
down_revision: str | None = '3237af62fd9d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'agents',
        sa.Column('video_provider', sa.String(length=20), nullable=False, server_default='openai'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'video_provider')
    # ### end Alembic commands ###
