"""add order status, is_unified and survey fields

Revision ID: 80e609a9e499
Revises: 2a6f92b661ec
Create Date: 2026-07-24 17:09:06.707151
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80e609a9e499'
down_revision: str | None = '2a6f92b661ec'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('is_unified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('orders', sa.Column('survey_note', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('survey_comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'survey_comment')
    op.drop_column('orders', 'survey_note')
    op.drop_column('orders', 'is_unified')
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###
