"""add agent usage_instructions and output_action

Revision ID: 9d8274569d7c
Revises: cd8675da5885
Create Date: 2026-07-25 20:52:23.674690
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d8274569d7c'
down_revision: str | None = 'cd8675da5885'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('usage_instructions', sa.Text(), nullable=True))
    op.add_column(
        'agents',
        sa.Column('output_action', sa.String(length=50), nullable=False, server_default='none'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'output_action')
    op.drop_column('agents', 'usage_instructions')
    # ### end Alembic commands ###
