"""add orders integration/created_at index

Revision ID: be36f8869f6e
Revises: 33f5d69cc60e
Create Date: 2026-07-24 16:24:19.693903
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "be36f8869f6e"
down_revision: str | None = "33f5d69cc60e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_orders_integration_created_at", "orders", ["integration_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_orders_integration_created_at", table_name="orders")
    # ### end Alembic commands ###
