from typing import Protocol, runtime_checkable


@runtime_checkable
class CacheProtocol(Protocol):
    async def get(self, key: str) -> str | None: ...
    async def set(self, key: str, value: str, ttl: int | None = None) -> None: ...
    async def delete(self, key: str) -> None: ...
    async def ping(self) -> bool: ...
